spring:
  application:
    name: smarttask

  datasource:
    url: jdbc:h2:mem:smarttaskdb
    driver-class-name: org.h2.Driver
    username: smarttask
    password: smarttask

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
    datasource:
      url: jdbc:h2:mem:smarttaskdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method